name: conference_app
description: A Flutter application for conference management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.1.0
  google_fonts: ^4.0.3
  intl: ^0.18.0
  cupertino_icons: ^1.0.5
  
  dio: ^5.3.2
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  internet_connection_checker: ^1.0.0
  
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  integration_test:
    sdk: flutter
  
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true